steps:
  - name: maven:3-jdk-11
    id: Maven build
    entrypoint: mvn
    args:
      - clean
      - install
      - "-T 2C"
      - "--no-transfer-progress"
      - "-DskipTests"
      - "-Ddisable-initializr-default-profile"
      - "-Dmaven.repo.local=/workspace/m2"
  - name: gcr.io/k8s-skaffold/pack
    id: Maven jib
    env:
      - LOCOREPO_DOCKER_IMAGE='$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    dir: "initializr-locorepo"
    entrypoint: /workspace/mvnw
    args:
      - "jib:dockerBuild"
      - "-T 2C"
      - "-Dmaven.repo.local=/workspace/m2"
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: europe-west1
  _LABELS: gcb-trigger-id=99d11cc8-cd13-4d84-86e7-3b9e5dea543d
  _TRIGGER_ID: 99d11cc8-cd13-4d84-86e7-3b9e5dea543d
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: initializr-locorepo
  _ENTRYPOINT: mvnw clean deploy
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - initializr-locorepo
